baseURL = "https://rlille.github.io/"
languageCode = "fr-FR"
title = "R Lille"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
publishDir = "../rlille.github.io"

[params]
    author = "R Lille"
    description = "Site internet du groupe des utilisateurs de R de Lille."
    githubUsername = "RLille"
    accent = "#d40000"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["r", "go", "haskell", "kotlin", "scala", "swift"]
    dateFormat = "02-01-2006" # "2006-01-02"
    logo = "/logo/rlille_small.png"
    logoSupport = "/logo/RConsortium_Horizontal_Pantone.png"

[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "À Propos"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/RLille"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.meetup.com/fr-FR/R-Lille/"
    name = "meetup"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
